defaults:
  - _self_
  - callbacks: custom_calvin_alltrain
  - datamodule: custom_calvin_alltrain
  - model: flower
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

root_data_dir: /home/jack/flower_vla_calvin/multi_task_dataset_raw_action_alltrain
lang_folder: lang_clip_resnet50

log_dir: /data2/jack/log
slurm: false
seed: 242
device: 'cuda'
batch_size: 16
devices: 2
act_dim: 7
proprio_dims: 13
obs_dim: 512
goal_dim: 512
obs_seq_len: 1
act_seq_len: 10
multistep: 10
p_last_state: 0
gen_img_res: 112
max_epochs: 20
num_workers: 4
benchmark_name: custom_flower
use_extracted_rel_actions: false

trainer:
  devices: ${devices}
  precision: 16-mixed
  max_epochs: ${max_epochs}
  sync_batchnorm: false
  accelerator: gpu
  strategy: "ddp"
  limit_train_batches: 1.0
  limit_val_batches: 0
  num_sanity_val_steps: 0

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ${log_dir}
  name: jack_usb_training
  group: vla_real_data
  project: flower_vla_Multi_Finetune_proprio_ft_raw
  entity: hjm20720-d
  id: ???

model:
  load_pretrained: True
  pretrained_model_path: /home/jack/flower_vla_calvin/flower_vla_pret/360000_model_weights.pt
  lowdim_obs_dim: 11

hydra:
  run:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_seed${seed}
  sweep:
    dir: ${log_dir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - datamodule.root_data_dir
          - trainer.gpus
          - datamodule.num_workers
          - trainer.limit_train_batches
          - trainer.limit_val_batches
