defaults:
  - transforms: calvin_transforms_color_aug

_target_: flower.datasets.hulc_data_module.HulcDataModule
_recursive_: false

root_data_dir: ${root_data_dir}
use_validation: false
action_space: 7
action_max: [1., 1., 1., 1., 1., 1., 1.]
action_min: [-1., -1., -1., -1., -1., -1., -1.]
shuffle_val: false

observation_space:
  rgb_obs: ['rgb_static', 'rgb_gripper']
  depth_obs: []
  state_obs: ['robot_obs']
  actions: ['rel_actions']
  language: ['language']

proprioception_dims:
  n_state_obs: 11
  keep_indices: [[2, 13]]
  normalize: false
  normalize_robot_orientation: false

datasets:
  lang_dataset:
    _target_: flower.datasets.disk_dataset.ExtendedDiskDataset
    key: "lang"
    save_format: "npz"
    batch_size: ${batch_size}
    min_window_size: ${act_seq_len}
    max_window_size: ${act_seq_len}
    proprio_state: ${datamodule.proprioception_dims}
    obs_space: ${datamodule.observation_space}
    skip_frames: 1
    pad: false
    lang_folder: ${lang_folder}
    aux_lang_loss_window: 8
    num_workers: ${num_workers}
    action_seq_len: ${act_seq_len}
    obs_seq_len: ${obs_seq_len}
    future_range: 1
    use_extracted_rel_actions: ${use_extracted_rel_actions}
    load_bbox: ${model.bbox_loss}
    bbox_key: ${model.bbox_key}
    bbox_rgb_key: rgb_static
